// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXl6YK5r5XW48nyOXcdc7Dba-juz9X1Gg',
    appId: '1:532731064289:web:78a5baf9251d0a909e6ca0',
    messagingSenderId: '532731064289',
    projectId: 'vicleco-moip-man-p',
    authDomain: 'vicleco-moip-man-p.firebaseapp.com',
    storageBucket: 'vicleco-moip-man-p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNXLm0INBVOWXlajDjOdBmSh-tLhVh1A',
    appId: '1:532731064289:android:86ed5fafd102d0799e6ca0',
    messagingSenderId: '532731064289',
    projectId: 'vicleco-moip-man-p',
    storageBucket: 'vicleco-moip-man-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3RJSYzvz40r_AzNBdGMzF99xKzK2fPhI',
    appId: '1:532731064289:ios:f60e461de9d922369e6ca0',
    messagingSenderId: '532731064289',
    projectId: 'vicleco-moip-man-p',
    storageBucket: 'vicleco-moip-man-p.appspot.com',
    androidClientId: '532731064289-cou9o4d684mjt5s3l9h42314j28ca920.apps.googleusercontent.com',
    iosClientId: '532731064289-6938sr9bjad8d1mpsp3baor6v2jg771f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moip',
  );
}
